# Spring properties
spring:
    application:
        name: api-gateway  # Identify this application

# Server
server:
    port: 8080   # HTTP (Tomcat) port

# Discovery Server Access
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8083/eureka/

# Api-Gate-Way
#zuul:
#    prefix: /api-gateway
#    routes:
#        filme-service:
#                path: /filme-sevice/**
#                serviceId: filme-sevice
#        cinema-service:
#                path: /cinema-sevice/**
#                serviceId: cinema-sevice


# Increase the Hystrix timeout to 60s (globally)
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000