server:
    port: 8086

spring:
    application:
           name: cinema-service
    profiles:
           active: dev


# Discovery Server Access
eureka:
    client:
           serviceUrl:
                  defaultZone: http://localhost:8083/eureka/
instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION


feign:
    hystrix:
        enabled: true
