server:
    port: 8084

spring:
    application:
           name: filme-service

# Discovery Server Access
eureka:
    client:
           serviceUrl:
                  defaultZone: http://localhost:8083/eureka/
instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION